#!/bin/bash
#PBS -l select=1:ncpus=24:nodetype=haswell_reg
#PBS -P CBBI0905
#PBS -q smp
#PBS -l walltime=1:00:00
#PBS -o /home/wsmidt/outputs/train25.out
#PBS -e /home/wsmidt/outputs/train25.err

#PBS -N trainingmap_train25
#PBS -M dejager4@gmail.com

mkdir -p /home/wsmidt/lustre/chpc_lecture/train25

module add chpc/BIOMODULES
module load bowtie2/2.2.9
module load samtools/1.3.1
module load bcftools/1.3.1

cd /home/wsmidt/lustre/chpc_lecture/train25

bowtie2 -p 24 -x IAI39 -1 reads1.fastq.gz -2 reads2.fastq.gz -S IAI39map.sam
samtools view -@ 24 -but IAI39.fasta IAI39map.sam > IAI39map.bam
samtools sort IAI39map.bam > IAI39map.sorted.bam
samtools mpileup -uf IAI39.fasta ./IAI39map.sorted.bam > IAI39map.sorted.mpileup
bcftools call –output-type v –ploidy 1 -v -c -V indels IAI39map.sorted.mpileup > IAI39.vcf

